// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4HKGmuONkbUczNfus_GiNIGM3UxYQ2o',
    appId: '1:817896901285:android:518308825f27799de4db4c',
    messagingSenderId: '817896901285',
    projectId: 'thriveapp-182a7',
    storageBucket: 'thriveapp-182a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMqbc3_kVDMKciRG8jUF-CAh33oQw-OOo',
    appId: '1:817896901285:ios:1a96a33245c6bdeee4db4c',
    messagingSenderId: '817896901285',
    projectId: 'thriveapp-182a7',
    storageBucket: 'thriveapp-182a7.firebasestorage.app',
    androidClientId: '817896901285-mlutkem12cl5i4nrbgbjns8md75i6o44.apps.googleusercontent.com',
    iosClientId: '817896901285-34c2eu8uhmfft0q9f3dpde7sflbv2iqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.thriveapp',
  );
}
